language: java
jdk: oraclejdk8
git:
  depth: 1
branches:
  only:
  - master

matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system

before_install:
  - sudo apt-get install -y ant

install:
  - true

script:
  - ant -f build-mac-ios.xml -v